[package]
name = "tomato-exporter"
version = "0.9.1"
authors = ["Christopher Lieb <chris.lieb@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
actix-web = "~4.4.1"
async-trait = "~0.1.77"
clap = { version = "~4.4", features = [ "cargo" ] }
dyn-clone = "~1.0.16"
futures = "~0.3.30"
maplit = "~1.0"
regex = "~1.10"
reqwest = { version = "~0.11", features = [ "rustls-tls" ], default-features = false }
serde = { version = "~1.0", features = [ "derive" ] }
serde_yaml = "~0.9"
time = "~0.3.31"
tracing = "~0.1.40"
tracing-actix-web = "~0.7.9"
tracing-log = "~0.2.0"
tracing-subscriber = "~0.3.18"
url = "~2.5.0"

[target.'cfg(windows)'.dependencies]
nu-ansi-term = "~0.50.0"
