[package]
name = "tomato-exporter"
version = "0.8.6"
authors = ["Christopher Lieb <chris.lieb@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
actix-rt = "~1.1"
actix-web = { version = "~3.0", features = [ "rustls" ] }
async-trait = "~0.1.40"
clap = "~2.33.3"
dyn-clone = "~1.0.2"
futures = "~0.3.5"
log = "~0.4"
maplit = "~1.0"
regex = "~1.3"
serde = { version = "~1.0", features = [ "derive" ] }
serde_yaml = "~0.8"
simplelog = "~0.8"
time = "~0.2.19"
url = "~2.1.1"
