[package]
name = "tomato-exporter"
version = "0.8.6"
authors = ["Christopher Lieb <chris.lieb@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
actix-rt = "~1.1"
actix-web = "~3.1"
async-trait = "~0.1.41"
clap = "~2.33.3"
dyn-clone = "~1.0.3"
futures = "~0.3.6"
log = "~0.4"
maplit = "~1.0"
regex = "~1.4"
reqwest = { version = "~0.10", features = [ "rustls-tls" ], default-features = false }
serde = { version = "~1.0", features = [ "derive" ] }
serde_yaml = "~0.8"
simplelog = "~0.8"
time = "~0.2.22"
url = "~2.1.1"
