[package]
name = "tomato-exporter"
version = "0.5.0"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
edition = "2018"

[dependencies]
actix-rt = "~1.1"
actix-web = "~2.0"
async-trait = "~0.1.38"
clap = "~2.33.3"
dyn-clone = "~1.0.2"
futures = "~0.3.5"
log = "~0.4"
maplit = "~1.0"
regex = "~1.3"
reqwest = { version = "~0.10", features = [ "blocking" ] }
serde = { version = "~1.0", features = [ "derive" ] }
serde_json = "~1.0"
serde_yaml = "~0.8"
simplelog = "~0.8"
url = "~2.1.1"
