[package]
name = "tomato-exporter"
version = "0.9.1"
authors = ["Christopher Lieb <chris.lieb@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
actix-web = "~4.0"
async-trait = "~0.1.56"
clap = { version = "~3.1", features = [ "cargo" ] }
dyn-clone = "~1.0.5"
env_logger = "~0.9.0"
futures = "~0.3.21"
log = "~0.4"
maplit = "~1.0"
regex = "~1.5"
reqwest = { version = "~0.11", features = [ "rustls-tls" ], default-features = false }
serde = { version = "~1.0", features = [ "derive" ] }
serde_yaml = "~0.8"
time = "~0.3.9"
url = "~2.2.2"
