[package]
name = "tomato-exporter"
version = "0.9.1"
authors = ["Christopher Lieb <chris.lieb@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
actix-web = "~4.3.1"
async-trait = "~0.1.73"
clap = { version = "~4.4", features = [ "cargo" ] }
dyn-clone = "~1.0.13"
futures = "~0.3.28"
maplit = "~1.0"
regex = "~1.9"
reqwest = { version = "~0.11", features = [ "rustls-tls" ], default-features = false }
serde = { version = "~1.0", features = [ "derive" ] }
serde_yaml = "~0.9"
time = "~0.3.27"
tracing = "~0.1.37"
tracing-actix-web = "~0.7.6"
tracing-log = "~0.1.3"
tracing-subscriber = "~0.3.17"
url = "~2.4.0"

[target.'cfg(windows)'.dependencies]
nu-ansi-term = "~0.49.0"
