[package]
name = "tomato-exporter"
version = "0.9.1"
authors = ["Christopher Lieb <chris.lieb@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
resolver = "2"

[dependencies]
actix-rt = "~1.1"
actix-web = "~3.3"
async-trait = "~0.1.51"
clap = "~2.33.3"
dyn-clone = "~1.0.4"
futures = "~0.3.17"
log = "~0.4"
maplit = "~1.0"
regex = "~1.5"
reqwest = { version = "~0.10", features = [ "rustls-tls" ], default-features = false }
serde = { version = "~1.0", features = [ "derive" ] }
serde_yaml = "~0.8"
simplelog = "~0.10"
time = "~0.3.2"
url = "~2.2.2"
