[package]
name = "tomato-exporter"
version = "0.1.0"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.7", features = [ "blocking" ] }
serde = { version = "1.0.114", features = [ "derive" ] }
serde_yaml = "0.8.13"
