[package]
name = "tomato-exporter"
version = "0.1.0"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
edition = "2018"

[dependencies]
actix-rt = "~1.1"
actix-web = "~2.0"
clap = "~2.33.3"
log = "~0.4"
regex = "~1.3"
reqwest = { version = "~0.10", features = [ "blocking" ] }
serde = { version = "~1.0", features = [ "derive" ] }
serde_json = "~1.0"
serde_yaml = "~0.8"
simplelog = "~0.8"

[dev-dependencies]
maplit = "~1.0"
